gravity: [0, 0, -9.81]
time_step: 0.004166666666666667 # 1/240
ghost_start_pos: [0, 0, 0]
robot_start_pos: [0, 0, 0]
motor_pid:
  force: 50
  position_gain: 0.3
  velocity_gain: 1.0
urdf_paths:
  ghost: "urdf/glove.urdf"
  robot: "urdf/robotic_arm.urdf"
